### ISSUE TITLE
reading all fails with -a

### ISSUE THREAD

**Issue by pcnate** [thisdavej/ds18b20-raspi#3]
option `-a` does not function the same as `--all`

pi@raspi-1wire:~ $ `ds18b20 -a`
Error: found multiple 1-Wire sensors so readSimple methods cannot be used. Found the following device Ids: 28-0000068b6dfd, 28-0000068b6fe9, 28-0000068be415
null degC
pi@raspi-1wire:~ $ `ds18b20 --all`

| Device Id | Temp (degC) |
| -- | -- |
| 28-0000068b6dfd | 24.25 |
| 28-0000068b6fe9 | 23.437 |
| 28-0000068be415 | 23.875 |

**Comment by thisdavej** [comment]
Thanks for letting me know @pcnate!  I fixed the issue and published to npm.

**Comment by pcnate** [comment]
Thank you!!!

You can add "fixed #3" to the end of your commit message to close this automatically when pushed into the master branch. I push to a branch, then use a PR to merge into master once everything is tested. The commit message will put a reference to the commit in the issue log once it is pushed to github.

**Comment by thisdavej** [comment]
Very awesome, @pcnate.  Thanks for taking the time to provide those GitHub tips!  I'm still fairly new in the GitHub world and this will definitely help me improve my workflow.
