### ISSUE TITLE
temp returns as freezing

### ISSUE THREAD

**Issue by pcnate** [thisdavej/ds18b20-raspi#4]
Sometimes when a sensor is disconnected or connected it will return 0C and 32F. It should return null if there is any way to detect that the data is messed up

**Comment by thisdavej** [comment]
Thanks for submitting this issue, @pcnate.  I was able to reproduce the "freezing temp" you were experiencing using a ds18b20 sensor on my side.  The problem should be fixed with this latest release.

**Comment by pcnate** [comment]
Awesome. I'll get it tested
